[package]
name = "shn2xml"
version = "0.1.0"
authors = ["skeleten <janpelle.thomson@stud.tu-darmstadt.de>"]

[dependencies]
shn = { git = "https://github.com/skeleten/shn-rs" }
xml-rs = "0.3.0"
docopt = "0.6.78"
encoding = "0.2.32"
